---
- name: Create Jenkins group
  group:
    name: "{{ jenkins_config_group }}"
    state: present

- name: Create Jenkins user
  user:
    name: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    home: "{{ jenkins_home }}"
    shell: "/bin/false"
    state: present

- name: Install apt PPA dependencies
  apt:
    name: python-software-properties

- name: Install  PPA dependencies
  apt:
    name: software-properties-common
    state: present

- name: Add Java Repository
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Install the Debian keyring
  apt:
    name: debian-archive-keyring

- name: Add Debian experimental repository for OpenJDK
  apt_repository:
    repo: deb http://httpredir.debian.org/debian experimental main
    state: present

- name: Add Debian sid repository for OpenJDK
  apt_repository:
    repo: deb http://httpredir.debian.org/debian sid main
    state: present

- name: Create pinning file for apt
  copy:
    src: files/apt/debian-package-pins
    dest: /etc/apt/preferences.d/debian
    owner: root
    group: root
    mode: 0644

- name: Update APT package manager repositories cache
  apt:
    update_cache: no

- name: Install apt packages
  apt:
    name: "{{ jenkins_apt_packages }}"
    state: present

- name: Set default Java version
  shell: /usr/sbin/update-java-alternatives -s "{{ jenkins_java_version }}"  # noqa 305
  ignore_errors: true
  changed_when: false

#- name: Add Jenkins key
#  apt_key:
#    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
#    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Install Jenkins binary package
  apt:
    name: "jenkins={{ jenkins_version }}"
    state: present

- name: Install maven package
  apt:
    name: "maven=3.0.5-1"
    state: present

- name: Set JENKINS_HOME
  lineinfile:
    dest: /etc/default/jenkins
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='

- name: Set Jenkins port
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: "HTTP_PORT={{ jenkins_port }}"

- name: Set Jenkins command line options
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: "JAVA_ARGS=\"{{ jenkins_java_opts }}\""
